# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    description: Defines how to deploy the database
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2017-02-16T02:56:56Z
  generation: 10
  labels:
    app: joomla-mysql-persistent
    template: joomla-mysql-persistent
  name: mysql
  namespace: site-ng
  resourceVersion: "883281797"
  selfLink: /oapi/v1/namespaces/site-ng/deploymentconfigs/mysql
  uid: 93faaffe-f3f3-11e6-a1dd-0e63b9c1c48f
spec:
  replicas: 1
  selector:
    name: mysql
  strategy:
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: joomla-mysql-persistent
        name: mysql
      name: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: joomla-mysql-persistent
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: joomla-mysql-persistent
        - name: MYSQL_DATABASE
          value: default
        image: registry.access.redhat.com/rhscl/mysql-56-rhel7@sha256:34afcd94138a80c8624a113883e8a88c06168a89880ff262ed4455e846c73b1d
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - MYSQL_PWD='olnpDaFSnBCSjud3' mysql -h 127.0.0.1 -u joomla -D default
              -e 'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: mysql-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - mysql
      from:
        kind: ImageStreamTag
        name: mysql:latest
        namespace: openshift
      lastTriggeredImage: registry.access.redhat.com/rhscl/mysql-56-rhel7@sha256:34afcd94138a80c8624a113883e8a88c06168a89880ff262ed4455e846c73b1d
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-02-16T22:25:47Z
    message: Replication controller "mysql-3" has completed progressing
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2017-02-17T17:40:21Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - imageTrigger:
        from:
          kind: ImageStreamTag
          name: mysql:latest
          namespace: openshift
      type: ImageChange
    message: image change
  latestVersion: 3
  observedGeneration: 10
  replicas: 1
  updatedReplicas: 1
